version: "3.9"

services:
  #################################################
  # RDB — PostgreSQL
  #################################################
  postgres:
    image: postgres:16
    container_name: recruiting_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: recruiting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  #################################################
  # Vector DB — Qdrant
  #################################################
  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: recruiting_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"      # REST / gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    depends_on:
      - postgres         # （必須ではないが起動順を明示）

  #################################################
  # （任意）DB GUI — pgAdmin
  #################################################
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: recruiting_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  qdrant_data:
  pgadmin_data:
